"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""
ant_fib = 0
fib = 0
suma = 0

for i in range(1, 4000000):
    if i == 1:
        ant_fib = fib = 1
    elif i == 2:
        fib = suma = 2
    else:
        fib = ant_fib + fib
        ant_fib = fib - ant_fib
        if fib % 2 == 0:
            suma = suma + fib
    if i < 50:
        print "({0}): {1} | {2}".format(i, fib, fib % 2 == 0)
    if fib >= 4000000:
        # print ant_fib
        break

print "SUMA: {0}".format(suma)
